### ISSUE TITLE
Dataset decoupled from dependencies in Database - can not be updated - needs to be fixed "by hand".

### ISSUE THREAD

**Issue by stvdwtt** [materials-commons/materialscommons.org#1000]
I created and published a dataset ("Composition and Morphology of an Isolated Mg-Nd β''' Precipitate"). I wanted to go back and add more authors to it. I unpublished it, added the new authors, and republished it. The new authors don't show up on the Materials Commons Data site. As I entered the new authors I kept getting "Error: Unable to update dataset" messages in the top right of the screen.

While published, if I try to make any changes to the dataset description (changing the name, the description field, etc), I get the same warning.

**Comment by Terry-Weymouth** [comment]
@stvdwtt -- I was unable to duplicate this problem.
Specifically, I was able to carry out the following steps without error...

1. Select an Experiment
2. Create a new Dataset
3. Add Processes steps to the dataset
4. Add an Author
5. Publish the dataset
6. Verify that the author is shown
7. Un-publish the dataset
8. Add another Author
9. Publish the dataset
10. Verify that the second author is shown
11. Un-publish the dataset
12. Change the title and description
13. Publish the dataset
14. Verify that the title and description were changed

I would very much like to duplicate the problem you are seeing; otherwise I will not be able to fix it. So, I am wondering if you could give a more complete step-by-step description of the steps you carry out to produce the error.

Thanks.
Terry.

**Comment by stvdwtt** [comment]
@Terry-Weymouth I checked and I'm still having the same problem. Here's exactly what I did.

1) Selected an existing experiment
2) Selected an existing and currently published dataset
3) Clicked "UNPUBLISH DATASET"
4) Added an author to the dataset (after I put it in I got a red "Error: Unable to update dataset" dialog box in the upper right corner. It disappears fast enough that I couldn't get a screenshot. The new name shows up in the data set screen (see below):
![image](https://cloud.githubusercontent.com/assets/10517751/26639643/6a5290f4-45f3-11e7-826c-4825961ea996.png)

5) Clicked Publish Dataset
6) Dataset is back on the public site, but without the new name (see below):
![image](https://cloud.githubusercontent.com/assets/10517751/26639714/99980722-45f3-11e7-9960-2c45a58e68f8.png)

**Comment by Terry-Weymouth** [comment]
@stvdwtt I'm looking at this problem again. I'm adding some notes so that Glenn and I can discuss.
Dataset Id = d78ada5c-1090-47f0-8633-534fac72de92;
Which project/experiment is this attached to?

**Comment by stvdwtt** [comment]
@Terry-Weymouth The project is "PF Simulation of Mg-Nd Preciptiates" and the experiment is "Composition and Morphology of an Isolated Mg-Nd B''' Precipitate".

**Comment by Terry-Weymouth** [comment]
@gtarcea Something is very odd about this dataset. It does not appear at the Projects site. That is, I made the following check:
1) Logged in a admin
2) Switched user to @stvdwtt 
3) Navigated to the above project
What I discovered is that the dataset (see id above) is not linked to an experiment in the project.
@stvdwtt is it possible that the experiment was deleted? (I believe that deleting an experiment when it has a dataset is not allowed, but I would have to check to be sure).
At any rate, I asked @gtarcea to look into this problem.

**Comment by Terry-Weymouth** [comment]
This appears to be a special case in which the underlying experiment or possibly project (or some other dependent line) was deleted, and hence the dataset can not be updated! If this is, in fact, the case, then @gtarcea or some other Materials Commons admin will have to fix the problem "by hand". Please work closely with him.

**Comment by Terry-Weymouth** [comment]
Note, the we recently put in code to prevent the deleting of an Experiment, Project, or Dataset when  there is a published dataset in the "path". And to assure that all unpublished dataset are deleted when a Project or Experiment (with only unpublished datasets) is deleted. Note, also, that a dataset with a DOI is considered to have been published, even if it is currently unpublished and (because of this) is can not be deleted, nor can a project/experiment that contains it be deleted.
