### ISSUE TITLE
Workflow Editor - Node deletion

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#708]
Currently nodes cannot be deleted in the workflow editor.

**Comment by Terry-Weymouth** [comment]
Suggestion is this: when selecting node in a graph, the node displays details on the right-side panel. Have a delete button that the use can click to delete the node. The button will only be enabled when the node is a leaf node; otherwise, it will be disabled, and a note will appear to the effect that nodes with dependencies can not be deleted, maybe "delete dependent nodes first".

**Comment by Terry-Weymouth** [comment]
This is done, with a first pass of testing. I've created a separate issue for 'full blown' automated testing on this added feature (see #773).
