### ISSUE TITLE
Cleanup how templates are represented in frontend/backend of Materials Commons

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#715]
Currently templates are represented in code on both the front end and back end. This makes handling templates problematical and finicky. Creating new templates means creating the same code on the front and back end. We should have a single representation for templates.

**Comment by Terry-Weymouth** [comment]
If we can change the middleware so that template configuration depends entirely on what is in the DB, then the first template editor can be a JSON editor. Then, to keep things socially simple, we could attach the template editing UI to the (new) Admin page, and only let users designated as admin do template editing. 

Links: 
- https://www.npmjs.com/package/json-editor
- https://www.npmjs.com/package/json-schema-editor
- https://www.npmjs.com/package/terriajs-catalog-editor
